# Generated by Django 5.1.3 on 2024-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_order_user_email_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
