# Generated by Django 5.1.3 on 2024-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='atId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
